openapi: 3.0.3
info:
  title: "Safe-Jeonse AI Report API"
  description: "전세 사기 위험도 AI 분석 리포트 API 명세서. 단일 엔드포인트를 통해 등기부등본 유무에 따라 상세도가 다른 통합 리포트를 제공합니다."
  version: "1.2.0"

tags:
  - name: "Analysis Report"
    description: "AI 기반 전세 위험도 분석 리포트 생성 API"

paths:
  /api/report:
    post:
      tags:
        - "Analysis Report"
      summary: "AI 전세 위험도 분석 리포트 생성"
      description: "매물 정보와 등기부등본(선택)을 받아 AI가 종합 분석한 리포트를 생성합니다. 파일 유무와 관계없이 항상 multipart/form-data로 요청해야 합니다."
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - address
                - leaseDeposit
              properties:
                address:
                  type: string
                  example: "서울특별시 강남구 테헤란로 123, 101동 202호"
                leaseDeposit:
                  type: number
                  example: 500000000
                landlord:
                  type: string
                  example: "홍길동"
                registryFile:
                  type: string
                  format: binary
                  description: "등기부등본 PDF 파일 (선택 사항)"

      responses:
        '200':
          description: "분석 성공. 등기부등본 첨부 여부에 따라 리포트의 상세 내용이 달라집니다."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalysisReport'
        '400':
          description: "잘못된 요청."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: "처리할 수 없는 파일."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: "서버 내부 오류."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    # --- 통합 성공 응답 스키마 (200 OK) ---
    AnalysisReport:
      type: object
      description: "AI 전세 위험도 통합 분석 리포트"
      properties:
        reportId:
          type: string
          format: uuid
          example: "f47ac10b-58cc-4372-a567-0e02b2c3d479"
        analysisType:
          type: boolean
          description: "등본 미첨부 시 false."
          enum: [true, false]
          example: true

        # 1. 위험도
        overallRiskLevel:
          type: string
          description: "AI가 판단한 종합 위험도 등급"
          enum: [안전, 주의, 위험, 고위험]
          example: "위험"

        # 2. 매물정보 (시세, 전세금, 전세가율)
        propertyInfo:
          type: object
          properties:
            address:
              type: string
              example: "서울특별시 강남구 테헤란로 123, 101동 202호"
            marketPrice:
              type: number
              description: "AI가 추정한 현재 매매 시세"
              example: 650000000
            leaseDeposit:
              type: number
              description: "사용자가 입력한 전세 보증금"
              example: 500000000
            riskRatio: # 등기부 등본이 없을시 포함 x
              type: number
              description: "전세가율 (%)"
              format: float
              example: 76.9

        # 3. 세부 위험 요소 분석
        detailedRiskAnalysis:
          type: array
          description: "AI가 분석한 세부 위험 요소 목록. 등기부등본 첨부 시 분석 항목이 추가됩니다."
          items:
            $ref: '#/components/schemas/RiskItem'

        # 4. AI 종합 코멘트
        aiGeneralComment:
          type: string
          description: "분석 결과를 종합한 AI의 최종 코멘트"
          example: "종합 분석 결과, 전세가율이 다소 높고 등기부등본상 선순위 채권이 존재하여 보증금 반환에 위험이 따를 수 있습니다. 계약 전 추가 확인이 반드시 필요합니다."

        # 5. AI로 확인하기 어려운 추가 체크사항
        humanChecklist:
          type: array
          description: "AI가 확인할 수 없는, 사용자가 직접 확인해야 할 중요 체크리스트"
          items:
            $ref: '#/components/schemas/ChecklistItem'

    RiskItem:
      type: object
      properties:
        category:
          type: string
          description: "분석 항목 (예: 전세가율, 건축물 정보, 등기부등본 소유주)"
          example: "선순위 채권 분석"
        riskLevel:
          type: string
          description: "항목별 위험 등급"
          enum: [안전, 주의, 위험]
          example: "위험"
        comment:
          type: string
          description: "항목별 분석 코멘트"
          example: "선순위 근저당 채권최고액이 1.5억 원 설정되어 있어, 주택 시세 대비 부채 비율이 높습니다."

    ChecklistItem:
      type: object
      properties:
        title:
          type: string
          description: "체크리스트 항목 제목"
          example: "임대인 신분증 확인"
        description:
          type: string
          description: "확인해야 할 구체적인 내용과 방법"
          example: "계약 당일, 등기부등본상 소유주와 임대인의 주민등록증 이름 및 얼굴이 일치하는지 반드시 대조 확인하세요."
        isEssential:
          type: boolean
          description: "필수 확인 여부"
          example: true

    # --- 공통 에러 응답 스키마 ---
    ErrorResponse:
      type: object
      required:
        - errorCode
        - message
      properties:
        errorCode:
          type: string
          example: "INVALID_DATA_FORMAT"
        message:
          type: string
          example: "입력된 주소 또는 전세 보증금의 형식이 올바르지 않습니다."